CXX ?= g++

CXXFLAGS += -c -Wall $(shell pkg-config --cflags opencv)
LDFLAGS += $(shell pkg-config --libs --static opencv)

all: seamlessClone_OpenCV

seamlessClone_OpenCV: seamlessClone_OpenCV.o; $(CXX) $< -o $@ $(LDFLAGS)

%.o: %.cpp; $(CXX) $< -o $@ $(CXXFLAGS)

clean: ; rm -f seamlessClone_OpenCV.o seamlessClone_OpenCV
